apiVersion: {{ .metadata.apiVersion }}
kind: GameDeployment
{{ include "custom.gdeployMetadata" . }}
spec:
  selector:
    matchLabels:
      {{- include "common.labelSlice2Map" .metadata.labels | indent 6 }}
  replicas: {{ .spec.replicas.cnt | default 0 }}
  updateStrategy:
    type: {{ .spec.replicas.updateStrategy }}
    partition: {{ .spec.replicas.partition | default 0 }}
    maxUnavailable: {{ .spec.replicas.maxUnavailable | default 0 }}{{ if and (.spec.replicas.maxUnavailable) (eq .spec.replicas.muaUnit "percent") }}% {{ end }}
    maxSurge: {{ .spec.replicas.maxSurge | default 0 }}{{ if and (.spec.replicas.maxSurge) (eq .spec.replicas.msUnit "percent") }}% {{ end }}
    {{- if eq .spec.replicas.updateStrategy "InplaceUpdate" }}
    inPlaceUpdateStrategy:
      gracePeriodSeconds: {{ .spec.replicas.gracePeriodSecs | default 0 }}
    {{- end }}
  {{- if .spec.gracefulManage.preDeleteHook.enabled }}
  preDeleteUpdateStrategy:
    {{- include "custom.gdeployUpdateHook" .spec.gracefulManage.preDeleteHook | nindent 4 }}
  {{- end }}
  {{- if .spec.gracefulManage.preInplaceHook.enabled }}
  preInplaceUpdateStrategy:
    {{- include "custom.gdeployUpdateHook" .spec.gracefulManage.preInplaceHook | nindent 4 }}
  {{- end }}
  {{- if .spec.gracefulManage.postInplaceHook.enabled }}
  postInplaceUpdateStrategy:
    {{- include "custom.gdeployUpdateHook" .spec.gracefulManage.postInplaceHook | nindent 4 }}
  {{- end }}
  {{- if .spec.gracefulManage.preInplaceHook }}
  {{- end }}
  {{- if .spec.gracefulManage.postInplaceHook }}
  {{- end }}
  minReadySeconds: {{ .spec.replicas.minReadySecs | default 0 }}
  {{- include "workload.podTemplate" . | nindent 2 }}
