apiVersion: {{ .metadata.apiVersion }}
kind: StatefulSet
{{ include "common.metadata" .metadata }}
spec:
  selector:
    matchLabels:
      {{- include "common.labelSlice2Map" .metadata.labels | indent 6 }}
  replicas: {{ .spec.replicas.cnt | default 0 }}
  {{- if .spec.replicas.svcName }}
  serviceName: {{ .spec.replicas.svcName }}
  {{- end }}
  strategy:
    type: {{ .spec.replicas.updateStrategy }}
  {{- if .spec.replicas.podManPolicy }}
  podManagementPolicy: {{ .spec.replicas.podManPolicy }}
  {{- end }}
  {{- include "workload.podTemplate" . | nindent 2 }}
  {{- include "workload.stsVolumeClaimTmpl" . | indent 2 }}
