.*/bcs-common/pkg/scheduler/mesosproto/.*
.*/bcs-k8s/bcs-gamedeployment-operator/pkg/apis/.*
.*/bcs-k8s/bcs-gamedeployment-operator/pkg/clientset/.*
.*/bcs-k8s/bcs-gamedeployment-operator/pkg/informers/.*
.*/bcs-k8s/bcs-gamedeployment-operator/pkg/listers/.*
.*/bcs-k8s/bcs-gamestatefulset-operator/pkg/apis/.*
.*/bcs-k8s/bcs-gamestatefulset-operator/pkg/clientset/.*
.*/bcs-k8s/bcs-gamestatefulset-operator/pkg/informers/.*
.*/bcs-k8s/bcs-gamestatefulset-operator/pkg/listers/.*
.*/bcs-k8s/kubedeprecated/.*
.*/bcs-k8s/kubernetes/.*
.*/bcs-mesos/bcs-container-executor/mesos/.*
.*/bcs-mesos/bcs-process-executor/process-executor/protobuf/.*
.*/bcs-mesos/bcs-scheduler/src/mesosproto/.*
.*/bcs-mesos/mesosv2/.*
.*/bcs-mesos/pkg/.*
.*/bcs-network/api/.*
.*/bcs-services/bcs-clb-controller/apis/.*
.*/bcs-services/bcs-clb-controller/client/.*
.*/bcs-services/bcs-log-manager/app/api/proto/.*
.*/bcs-services/bcs-log-manager/pkg/apis/.*
.*/bcs-services/bcs-log-manager/pkg/controllers/.*
.*/bcs-services/bcs-log-manager/pkg/generated/.*
.*/bcs-services/bcs-log-manager/pkg/mock/.*
.*/bcs-services/bcs-mesh-manager/api/.*
.*/bcs-services/bcs-mesh-manager/proto/.*
.*/bcs-services/bcs-mesh-manager/third_party/.*
.*/bmsf-configuration/internal/protocol/.*
.*/bmsf-mesh/pkg/.*
.*/innerdocs/.*
.*/install/conf/bcs-network/bcs-cloud-netservice/swagger-ui/.*
.*/pkg/mod/.*
