apiVersion: v1
kind: Service
metadata:
  name: bcs-federated-apiserver
  namespace: bcs-system
  labels:
    api: bcs-federated-apiserver
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: bcs-federated-apiserver
    apiserver: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bcs-federated-apiserver
  namespace: bcs-system
  labels:
    api: bcs-federated-apiserver
    apiserver: "true"
spec:
  selector:
    matchLabels:
      api: bcs-federated-apiserver
      apiserver: "true"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        api: bcs-federated-apiserver
        apiserver: "true"
    spec:
      serviceAccountName: bcs-federated-apiserver
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: bcs-federated-apiserver
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        command:
        - "./bcs-federated-apiserver"
        args:
        - "--etcd-servers=http://etcd-svc:2379"
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: apiserver-certs
        secret:
          secretName: bcs-federated-apiserver
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: bcs-federated-apiserver
  namespace: bcs-system
  labels:
    api: bcs-federated-apiserver
    apiserver: "true"
data:
  tls.crt: "{{ .Values.secret.tlsCrt }}"
  tls.key: "{{ .Values.secret.tlsKey }}"
