apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bcsegresses.bkbcs.tencent.com
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.namespace
    name: Namespace
    type: string
  - JSONPath: .metadata.name
    name: Name
    type: string
  - JSONPath: .status.state
    name: State
    type: string
  - JSONPath: .status.updateat
    name: UpdateAt
    type: date
  group: bkbcs.tencent.com
  names:
    kind: BCSEgress
    listKind: BCSEgressList
    plural: bcsegresses
    singular: bcsegress
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: BCSEgress is the Schema for the bcsegresses API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BCSEgressSpec defines the desired state of BCSEgress
          properties:
            controller:
              description: Controller can be empty, we use egress-controller.bcs-system
                for default
              properties:
                name:
                  default: egress-controller
                  type: string
                namespace:
                  default: bcs-system
                  type: string
              required:
              - name
              - namespace
              type: object
            rules:
              items:
                description: Rule is definition for forward proxy in controller
                properties:
                  destport:
                    type: integer
                  host:
                    description: Host for domain or iplist(split by comma) when http
                      protocol, host can use for acl
                    type: string
                  protocol:
                    enum:
                    - TCP
                    - HTTP
                    type: string
                  sourceport:
                    description: source & dest port use for tcp network flow control
                    type: integer
                required:
                - destport
                - host
                - protocol
                - sourceport
                type: object
              minItems: 1
              type: array
          required:
          - controller
          - rules
          type: object
        status:
          description: BCSEgressStatus defines the observed state of BCSEgress
          properties:
            reason:
              description: Reason when some error happened
              type: string
            state:
              description: State refference EgressState above
              type: string
            updateat:
              format: date-time
              type: string
          required:
          - reason
          - state
          - updateat
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
