# Default values for bcs-federated-apiserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
#wether create namespace bcs-system or not
createNamespace: false

fullnameOverride: "bcs-federated-apiserver"

image:
  registry: "mirrors.tencent.com"
  repository: "bcs/bcs-federated-apiserver"
  pullPolicy: Always

imagePullSecrets: []

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "250m"

nodeSelector: {}

tolerations: []

affinity: {}

configmap:
  bcsStorageAddress: "http://x.xxx.xx.xxx:xxxx"
  bcsStoragePodUri: "/bcsstorage/v1/dynamic/customresources/Pod"
  bcsStorageToken: ""
  memberClusterIgnorePrefix: "member."
  memberClusterOverride: "BCS-K8S-xxxxx"

secret:
  tlsCrt: ""
  tlsKey: ""

etcd:
  name: "bcs-federated-apiserver-etcd"
  svcName: "bcs-federated-apiserver-etcd-svc"

etcdImage:
  registry: "mirrors.tencent.com"
  repository: "bcs/etcd-federated-apiserver"
  tag: "v3.4.13"
  pullPolicy: Always
