# Default values for bcs-federated-apiserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
#wether create namespace bcs-system or not
createNamespace: false

image:
  repository: "xxxxxxx.xxxxxxx.xxx/xxx/bcs-federated-apiserver"
  pullPolicy: Always

imagePullSecrets: []

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "250m"

nodeSelector: {}

tolerations: []

affinity: {}

configmap:
  bcsStorageAddress: "http://x.xxx.xx.xxx:xxxx"
  bcsStoragePodUri: "/bcsstorage/v1/dynamic/customresources/Pod"
  bcsStorageToken: ""
  memberClusterIgnorePrefix: "member."
  memberClusterOverride: "BCS-K8S-xxxxx"

secret:
  tlsCrt: ""
  tlsKey: ""

etcdImage:
  repository: "xxxxxxx.xxxxxxx.xxx/xxx/etcd"
  tag: "v3.4.13"
  pullPolicy: Always
