apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    release: gamestatefulset
  name: gamestatefulsets.tkex.tencent.com
spec:
  group: tkex.tencent.com
  names:
    kind: GameStatefulSet
    listKind: GameStatefulSetList
    plural: gamestatefulsets
    singular: gamestatefulset
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
      labelSelectorPath: .status.labelSelector